- cmd/ksync/update.go
The `update` command appears to be working. May have unaddressed edge conditions, but usable for now.
> Expose the `ksync update` command.

- testdata/ci/release.sh
Limit releases to `ksync` only. Fixes #89
> Only push the `ksync` binaries to release

- Gopkg.lock
- Gopkg.toml
- cmd/ksync/update.go
This change should be considered temporary and should be reverted back to the original package if a more permanent solution is found.
> Switch to a fork of `overseer` to fix `update`. Fixes #94

- pkg/ksync/radar_test.go
We should only override the default image if the env var is set.
> Only override the pushed image if set

- pkg/ksync/spec.go
- pkg/ksync/syncthing.go
- pkg/syncthing/server.go
Fixes #143 
**tl;dr** When the tunnel to a cluster closes unexpectedly, `watch` loops continually. The loop stems from empty messages being streamed to a channel. See afbc00e for details.
> Cluster lost fix

- Gopkg.lock
- pkg/ksync/cluster/client.go
Attemping to run `ksync init` against a kubernetes cluster with a
kubectl context using OIDC authentication results the below error unless
ksync imports the k8s OIDC client auth plugin:
$ ./bin/ksync init
FATA[0000] No Auth Provider found for name "oidc"
> cluster/client: add support for k8s OIDC auth

- pkg/input/sync_path.go
- pkg/input/sync_path_test.go
This temporarily removes the check on local path permissions to ensure they match the writability of remote paths. It is intended to solve https://github.com/vapor-ware/ksync/issues/151 until a better solution is implemented.
Note: My 🧠 hurts.
Closes #151
> REVERT: Temporarily removes the check on permissions.

- cmd/ksync/get.go
Add's `Container Name` to the output table for `ksync get`.
Closes #155
> Add container name to output fields

- .circleci/config.yml
Allow for `-` "pre-release" style tags to also be recognized by CI for the release workflow.
https://semver.org/
> Allow semver 2.0 "pre-release" tags

- cmd/ksync/create.go
- pkg/ksync/doctor/local.go
- pkg/syncthing/server.go
Adds a hotfix for multiple specs being created at once leading to a race condition.
Ultimately this should be solved more gracefully.
Closes #145 
Closes #160
> Spec Creation Flood Protection

- cmd/ksync/get.go
Adds suppressed output for `get`, mostly for piping friendliness.
> Add `--quiet` output for `get`. Closes #165

- pkg/ksync/syncthing.go
If we're running on windows, don't try to clean up the daemon process (since it won't exist), just bail.
Closes #176
> Bail when using daemon commands in Windows

- .circleci/config.yml
Technically this isn't parallelism (defined [here](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-filesize)) because most of our long running processes are linear and can't be split. However, we can split out the various (relatively) independent jobs so that they run in parallel.
Closes #184
> Parallelism In CI

- cmd/ksync/get.go
Moving this flag to the global flag list changed `viper` instance it was attached to.
> Fixes #194

- pkg/ksync/doctor/kubernetes.go
Increase timeout to allow custom authenticators complete. Fixes issue connecting to EKS cluster.
> Increase K8S timeout to allow authenticators to complete

- cmd/ksync/get.go
Closes #200
Simple string matching search based on spec names.
> If args are submitted to `get` search on those terms.

- README.md
Whenever minikube is running with `vm-driver=none` option and socat
is not installed on the host, weird grpc errors will start to pop.
Hopefully this note will help others find a solution quicker than I did 😉
> Fix #227 Added a troubleshooting entry in the README

- Gopkg.lock
- Makefile
- cmd/ksync/daemon.go
- pkg/input/sync_path.go
- pkg/ksync/cluster/connection.go
- pkg/ksync/doctor/local.go
- pkg/ksync/folder.go
- pkg/ksync/server/restart.go
- pkg/ksync/syncthing.go
- pkg/syncthing/server.go
Update the daemon package from timfallmk/go-daemon to the upstream sevlyar/go-daemon which adds support for Windows.
Closes #256 
**Warning**: Only tested building on Windows. Functionality is experimental and untested.
> Daemon update

- cmd/ksync/clean.go
- cmd/ksync/ksync.go
- pkg/ksync/cluster/daemon_set.go
- pkg/ksync/cluster/service_test.go
And also allowing to pass custom paths to Docker sockets.
Both come in handy when using
https://github.com/kubernetes-sigs/kubeadm-dind-cluster
Signed-off-by: Jean Rouge <rougej+github@gmail.com>
> Fixing a small bug with non-default Docker roots

- pkg/ksync/cluster/connection.go
Solves https://github.com/vapor-ware/ksync/issues/310
This will fail ksync in case of this error, as it is anyway not recoverable.
> Fatal in case of radar connection error

- .github/workflows/publish.yml
- Makefile
Fills out info stamped into binary releases.
Fixes #320
> Add correct stamping data so releases get version info

- docs/development.md
I was following this document to build locally
https://github.com/ksync/ksync/blob/master/docs/development.md
It was failing with this error.
```
$ env | grep GO
GOROOT=/usr/local/go
GOPATH=/Users/alok87/gocode
```
```
$ go install cmd/*
can't load package: package cmd/ksync: package cmd/ksync is not in GOROOT (/Users/alok87/src/cmd/ksync)
can't load package: package cmd/radar: package cmd/radar is not in GOROOT (/Users/alok87/src/cmd/radar)
```
Adding a `./` fixes it.
```
$ go install ./cmd/*
works !
```
> Added ./ for it to able to resolve the path

- pkg/ksync/spec.go
**What?**
Typecast the event object only when the event is relevant.
Fixes https://github.com/ksync/ksync/issues/334
> Handle only the relevant events to prevent continuous crash

- docker/Dockerfile
See this link: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
> refactor(dockerfile): replace deprecated maintainer with label

- README.md
The URL: https://kubernetes.io/docs/setup/pick-right-solution/ was updated to: https://kubernetes.io/docs/setup/
One of their cleanup PRs where they replaced it:
https://github.com/kubernetes/website/pull/14468
> Fix broken Kubernetes doc link
