- .circleci/config.yml
- cmd/ksync/update.go
- testdata/build/stamps.sh
- testdata/ci/release.sh
See https://github.com/vapor-ware/ksync/compare/release-versions?expand=1#diff-c860d8d6e153d9a32df0a3ced416dfdeR9 for details.
https://circleci.com/gh/organizations/vapor-ware/settings#contexts
> Release versions

- README.md
- cmd/ksync/create.go
- pkg/input/sync_path.go
- pkg/ksync/spec_list.go
> Adding directory checking back in.

- .circleci/config.yml
Should cut down on the output for each release.
> Shorten the changelog to only include changes from this tag

- README.md
- pkg/ksync/mirror.go
- Fixes #100
- Fixes #93
- Fixes an issue where slow restarts of mirror would break syncs.
> Cleaning some outstanding bugs up.

- README.md
- cmd/ksync/update.go
- pkg/cli/config.go
- pkg/cli/flags_test.go
- pkg/input/sync_path.go
- pkg/input/sync_path_test.go
- pkg/ksync/doctor.go
- pkg/ksync/errors_test.go
- pkg/radar/info.go
- pkg/radar/path_test.go
- pkg/radar/restart_test.go
- pkg/radar/server_test.go
Cleaning out the belly button lint.
> Linting for wins

- README.md
- cmd/ksync/ksync.go
- pkg/cli/flags.go
- pkg/cli/tasks.go
- pkg/ksync/cluster/error_handler.go
- pkg/ksync/doctor/service.go
- pkg/ksync/doctor/versions.go
- pkg/ksync/folder.go
- pkg/ksync/service.go
- pkg/ksync/service_list.go
- pkg/ksync/spec.go
- pkg/syncthing/events.go
- pkg/syncthing/folder.go
- pkg/syncthing/server.go
> Cleaning things up from a usability perspective.

- .circleci/config.yml
We see the linting problems without the cache so adding this back to see if it changes anything.
> Re-adding cache to see if it works

- .circleci/config.yml
- pkg/input/sync_path.go
- pkg/ksync/syncthing.go
- testdata/ci/release.sh
When releasing a new version, upload binaries to our slack org.
Sorry outsiders, this ain't for you!
**Edit**: I guess it actually _could_ be for you, if you add your own variables.
> Slack upload

- README.md
- docs/README.md
- docs/offline.md
> Document offline usage

- cmd/ksync/delete.go
Changes `delete` to take in more than one name. This can be used for piping multiple deletes, particularly with `get -q`.
**Note**: At the moment this suffers from the same flooding problem that `create` does (#145), but this should be fixed soon.
Closes #168
> Allows for multiple inputs to `delete`

- cmd/ksync/delete.go
What's there to say? I did this because, why not? Take that!
Also kinda helps with #168 .... maybe
> Implements a `delete --all` option

- pkg/input/sync_path.go
- pkg/ksync/folder.go
> Windows path fix

- pkg/ksync/server/restart.go
Don't pass `nil` values to `protobuf` as it gets angry.
> Fixes #197

- pkg/ksync/syncthing.go
> Explicit file extensions are required on windows

- Gopkg.lock
- Gopkg.toml
- cmd/ksync/get.go
- cmd/ksync/ksync.go
- cmd/ksync/update.go
- pkg/ksync/cluster/daemon_set.go
- pkg/ksync/cluster/service.go
- pkg/ksync/cluster/tunnel.go
- pkg/ksync/doctor/kubernetes.go
- pkg/ksync/remote_container.go
- pkg/ksync/service_list.go
- pkg/ksync/spec.go
- pkg/ksync/syncthing.go
- pkg/syncthing/server.go
And hating life
Also fixes #209
Fuck k8s
> Updating a lot of k8s dependencies

- docs/architecture.md
Thanks for putting this document together! Very helpful for understanding what ksync is doing.
> Fix typos in architecture document

- pkg/syncthing/fetch.go
Changes to match https://github.com/syncthing/syncthing release name changes. Fixes #219
> Change binary file os matching

- Gopkg.lock
- Gopkg.toml
- pkg/radar/docker.go
- pkg/radar/restart.go
Update docker package versions and associated dependent packages.
> Solve transitive dependency problems

- Gopkg.lock
- pkg/radar/docker.go
- pkg/radar/restart.go
> Force docker to negotiate for a common client version

- example/frontend/package-lock.json
- example/frontend/package.json
> Update node packages for example

- README.md
> Added version mismatch error to troubleshooting section

- README.md
Added troubleshooting steps for #247 
[skip ci]
> Updated documentation with new troubleshooting case #247

- Gopkg.lock
- Gopkg.toml
Update the stupid `client-go` library.
> Client go update

- cmd/ksync/init.go
> Add flag for setting DS ns

- cmd/ksync/init.go
- cmd/ksync/ksync.go
- pkg/ksync/cluster/service.go
- pkg/ksync/cluster/service_test.go
> Move ds ns to hidden global flag

- cmd/ksync/create.go
- cmd/ksync/delete.go
- cmd/ksync/restart.go
- cmd/ksync/watch.go
- pkg/ksync/spec.go
- pkg/ksync/spec_list.go
- Use constructors to create objects
- Rename function to use `getDesiredSpecItems()`
- Info logs on ksync configuration changes being updated
> Few code changes for better reading and logging

- Gopkg.lock
- example/app/app.yaml
- example/frontend/frontend.yaml
- pkg/ksync/cluster/daemon_set.go
- pkg/ksync/cluster/service.go
- testdata/k8s/config/max-cpu.yaml
- testdata/k8s/config/test-app.yaml
- testdata/k8s/config/testing.yaml
This PR implements update of the Daemonset manifest to api `apps/v1`. 
Fixes #315
> Upgrade daemonset to apps/v1

- .github/release-drafter.yaml
- .github/workflows/publish.yml
Autogenerate basic release notes and automatically upload assets to a release.
> Create release notes and assets

- Makefile
> Reformat tags to show version properly.

- .github/workflows/publish.yml
> Switch to using a custom generated changelog

- .github/workflows/publish.yml
- .github/workflows/test.yml
- go.mod
You know what to do after the beep. ☎️
> Bump go versions everywhere

- pkg/syncthing/fetch.go
> Quick fix for updated syncthing release packaging.

- .github/workflows/publish.yml
- .github/workflows/test.yml
- Updates workflow action dependency versions.
- Fixes #415
> Updates to publish workflow

- .github/workflows/publish.yml
Sets `fetch-depth=0` for `actions/checkout@v2` in order to fetch all tags.
> checkout-update
